<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.io7m.primogenitor</groupId>
    <artifactId>com.io7m.primogenitor.lite</artifactId>
    <version>9.1.0</version>
  </parent>

  <groupId>org.thepalaceproject.webpub</groupId>
  <artifactId>org.thepalaceproject.webpub</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <packaging>pom</packaging>
  <name>org.thepalaceproject.webpub</name>
  <description>OPDS 2.0 Parser</description>
  <url>https://www.github.com/ThePalaceProject/android-webpub</url>

  <modules>
    <module>org.thepalaceproject.webpub.cmdline</module>
    <module>org.thepalaceproject.webpub.core</module>
    <module>org.thepalaceproject.webpub.tests</module>
  </modules>

  <properties>
    <!-- Configuration. -->
    <io7m.api.previousVersion>0.2.0</io7m.api.previousVersion>
    <io7m.java.requiredSDKBuildVersion>[25,26)</io7m.java.requiredSDKBuildVersion>
    <io7m.java.targetJavaVersion>17</io7m.java.targetJavaVersion>

    <checkstyle.skip>true</checkstyle.skip>
    <mdep.analyze.skip>true</mdep.analyze.skip>

    <!-- Dependencies. -->
    <com.fasterxml.jackson.version>2.20.1</com.fasterxml.jackson.version>
    <com.io7m.dixmont.version>2.1.0</com.io7m.dixmont.version>
    <com.io7m.quarrel.version>1.8.0</com.io7m.quarrel.version>
    <jqwik.version>1.9.3</jqwik.version>
    <kotlin.version>2.2.21</kotlin.version>
    <one.irradia.mime.version>1.1.1</one.irradia.mime.version>
    <org.junit.version>6.0.2</org.junit.version>
  </properties>

  <licenses>
    <license>
      <name>Apache 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <inceptionYear>2025</inceptionYear>

  <scm>
    <url>https://www.github.com/ThePalaceProject/android-webpub</url>
    <connection>scm:git:https://www.github.com/ThePalaceProject/android-webpub</connection>
    <developerConnection>scm:git:https://www.github.com/ThePalaceProject/android-webpub</developerConnection>
  </scm>

  <developers>
    <developer>
      <id>io7m</id>
      <name>io7m</name>
      <email>code@io7m.com</email>
      <url>https://www.io7m.com</url>
    </developer>
  </developers>

  <issueManagement>
    <url>https://ebce-lyrasis.atlassian.net/browse/</url>
    <system>Jira</system>
  </issueManagement>

  <distributionManagement>
    <snapshotRepository>
      <id>central</id>
      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
    </snapshotRepository>
  </distributionManagement>

  <ciManagement>
    <system>GitHub Actions</system>
    <url>https://www.github.com/ThePalaceProject/android-webpub/actions</url>
  </ciManagement>

  <prerequisites>
    <maven>3.0.4</maven>
  </prerequisites>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.osgi</groupId>
        <artifactId>org.osgi.annotation.bundle</artifactId>
        <version>2.0.0</version>
      </dependency>
      <dependency>
        <groupId>org.osgi</groupId>
        <artifactId>org.osgi.annotation.versioning</artifactId>
        <version>1.1.2</version>
      </dependency>
      <dependency>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-stdlib</artifactId>
        <version>${kotlin.version}</version>
      </dependency>

      <dependency>
        <groupId>com.io7m.dixmont</groupId>
        <artifactId>com.io7m.dixmont.core</artifactId>
        <version>${com.io7m.dixmont.version}</version>
      </dependency>

      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>${com.fasterxml.jackson.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>one.irradia.mime</groupId>
        <artifactId>one.irradia.mime.api</artifactId>
        <version>${one.irradia.mime.version}</version>
      </dependency>
      <dependency>
        <groupId>one.irradia.mime</groupId>
        <artifactId>one.irradia.mime.vanilla</artifactId>
        <version>${one.irradia.mime.version}</version>
      </dependency>

      <!-- Command-line. -->
      <dependency>
        <groupId>com.io7m.quarrel</groupId>
        <artifactId>com.io7m.quarrel.core</artifactId>
        <version>${com.io7m.quarrel.version}</version>
      </dependency>
      <dependency>
        <groupId>com.io7m.quarrel</groupId>
        <artifactId>com.io7m.quarrel.ext.logback</artifactId>
        <version>${com.io7m.quarrel.version}</version>
      </dependency>

      <!-- Logging -->
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>2.0.17</version>
      </dependency>
      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-classic</artifactId>
        <version>1.5.27</version>
      </dependency>

      <!-- Test suite -->
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>${org.junit.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>net.jqwik</groupId>
        <artifactId>jqwik-engine</artifactId>
        <version>${jqwik.version}</version>
      </dependency>
      <dependency>
        <groupId>net.jqwik</groupId>
        <artifactId>jqwik-api</artifactId>
        <version>${jqwik.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>kotlin-maven-plugin</artifactId>
          <groupId>org.jetbrains.kotlin</groupId>
          <version>${kotlin.version}</version>
        </plugin>
        <plugin>
          <groupId>com.io7m.stmp</groupId>
          <artifactId>string-template-maven-plugin</artifactId>
          <version>2.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
